### ISSUE TITLE
Installation von Abhängigkeiten schlägt fehl

### ISSUE THREAD

**Issue by gislars** [topicmaps-wuppertal/starkregen#1]
Ich wollte mir die Anwendung lokal installieren, bekam aber bei der Installation der Abhängigkeiten einen Fehler. Der [Zugriff](https://npm.pkg.github.com/download/@cismet-dev/react-cismap-rainhazardmaps/1.7.9/0e51418e77b06dd3d340003cbe208f7902561f11cb240b8e124c4bb4eff5c8e6) auf das Paket @cismet-dev/react-cismap-rainhazardmaps scheitert an einem "401 Unauthorized"

Gibt es das Paket auch öffentlich von einer anderen Quelle? Wie kann ich die Anwendung lokal nachbauen?

**Comment by helllth** [comment]
@cismet-dev/react-cismap-rainhazardmaps steht nicht unter einer open-source Lizenz zur Verfügung. Momentan vertreiben wir die Starkregengefahrenkarten unter einem Pauschalpaket. Die Entwicklungskosten habe sich noch nicht amortisiert. Deshalb haben wir uns entschieden das Pakte in dem u.a. der zeitliche Verlauf visualisiert wird (noch) nicht zu veröffentlichen.
